---
# Projet d automatisation d'une instance wordpress
# EPSI B2 2019/20

- name: Configuration commune pour le noeud de machine
  hosts: all
  remote_user: root

  roles:
   - common
   
- name: Deploiment et configuration du serveur de base de donnees
  hosts: dbservers
  remote_user: root
   
  roles:
   - db
   
- name: Deploiment de Apache, PHP et configuration de Wordpress
  hosts: webservers
  remote_user: root
   
  roles:
   - web