---
# This playbook is to perform common tasks.

- name: Activer le Firewall sur tout le noeud
  service: name=firewalld state=started enabled=yes
    
- name: Activer le Firewall sur le port 22
  firewalld: port=22/tcp permanent=true state=enabled immediate=yes
    
- name: Désactiver l'authentification ssh par mdp sur le noeud
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: restart ssh